### ISSUE TITLE
Review Datastore Entity

### ISSUE THREAD

**Issue by dterr** [googleinterns/trace#85]
### [P0] How Do We Store the Comments?
Current solution: Create an entity wrapper for the ```PlaceReviews``` custom object. 
Pro: Lower Time Complexity for populating front end.
Status: **Not functioning as expected.**

Proposed solution: Utilize datastore as only Entities that mimick a Java Comment object.
``` Entity {String place_id, String reviewText} ``` Each comment would have a unique internal ID that could be utilized in ```VotingServlet.java``` to upvote/downvote.
Pro: Lower space complexity in datastore.
Status: Proposed

Other solution: Have **2 types of entities** in the datastore. The comments from the previous, and _arrays containing the IDs of comments for each place_id_. This would allow for quicker population of reviews on the front end while maintaining the low space complexity of the proposed solution.
Pro: Time Complexity benefit of the current solution, space complexity benefit of the proposed solution.
Status: Proposed addition to next solution

**Comment by ccjeane** [comment]
Claudia & Erick post-sync discussion 
-> Places Reviews contains a hashset of reviewers and a list of comments where you can access their reviewer. Not necessary?
-> Comment.java needs id's otherwise can't access individual reviews. 
-> Each comment needs to be in datastore so can be accessed in javascript code easily. 
-> No rating history in place reviews
-> Datastore rating? Look into it.

**Comment by kcirerick** [comment]
All in all, datastore will have:
Reviews Entity
Place Entity
<a href="https://docs.google.com/document/d/1uE6jZZvf8LTdJfzkATmozQoPsROZIM5Y-yiA4c1UGY8/edit"> design doc</a>
